# Generated by Django 4.2.3 on 2023-08-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='flight_number',
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_name',
            field=models.CharField(default='hry', max_length=50),
            preserve_default=False,
        ),
    ]
