# Generated by Django 4.2.5 on 2023-09-07 07:57

from django.db import migrations, models
import flights.models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_remove_flight_flight_number_flight_flight_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='seat_number',
            field=models.CharField(default=flights.models.generate_unique_seat_number, max_length=10, unique=True),
        ),
    ]
